### ISSUE TITLE
Setup cloudfront for dopomoha site

### ISSUE THREAD

**Issue by rafamec** [openstreetmap-polska/ua-2022-map#23]

**Comment by daniel-j-h** [comment]
Hey folks, are you interested in an AWS CDK based infrastructure as code for this issue and also https://github.com/openstreetmap-polska/ua-2022-map/issues/22?

From what I'm seeing we are shipping a static website. We could do the following
- Have an S3 bucket where we push the static artifacts to (aws sync)
- Have a CloudFront distribution with an S3 origin
- Have a cert from CertManager for the distribution
- Have a DNS record to the distribution

I've done this in the past for static websites like blogs or frontend applications, and it worked quite well and there was no need for manually managed infra.

Two gotchas
- if we want CI/CD to deploy, we'll also need a deploy aws iam user, no biggie
- frontend apps with their own routers will need to use hash routes, e.g. `/#/login` instead of `/login` because the former will stay on the client while the latter will try and go to a non-existent s3 file. I have skimmed the code and from what I can tel we are fine here.

Let me know if there's interest in this and I can cut a pull request, to set it all up. You'll then have to run it n your end because only you have aws credentials at the moment.

**Comment by daniel-j-h** [comment]
@ttomasz does this mean it's no longer needed? Have you seen my comment, do you folks need help here or not? :smile:

**Comment by ttomasz** [comment]
Hi @daniel-j-h sorry for late reply and thanks for the tips. @rafamec managed to set up CloudFront in front of our server so we should be fine here. We are generating basemap with ukrainian names so we use the server anyway. I'll keep in mind the routing thing, didn't know that. Thanks!
